"""
tools/dfmea/case_router.py
───────────────────────────
Reads dfmea_case from state and sets a routing flag used by
LangGraph's conditional edge to branch into the correct sub-graph.

tools/dfmea/rag_context.py
───────────────────────────
Runs an internal RAG retrieval specifically for DFMEA context:
component history, known failure modes from past FMEAs, and
relevant standards. Output is injected into all downstream DFMEA prompts.

tools/dfmea/parse_import.py
────────────────────────────
Wraps your existing dfmea_universal_parser.py to parse an uploaded
xlsx file and extract elements, functions, and noise factors into state.
"""

from __future__ import annotations
from core.tool_base import BaseTool, ToolResult
from core.state import AgentState
from core.llm import get_llm, get_embeddings
from langchain_community.vectorstores import FAISS
from langchain_core.prompts import ChatPromptTemplate

# ── 1. Case Router ────────────────────────────────────────────────────────────

class CaseRouterTool(BaseTool):
    name        = "case_router"
    description = "Validates dfmea_case and sets routing metadata for conditional edges."
    reads       = ["dfmea_case", "dfmea_import_path"]
    writes      = ["error"]

    def run(self, state: AgentState) -> ToolResult:
        case = state.get("dfmea_case")
        if case not in ("new", "new_env", "design_change"):
            return {"error": f"Unknown dfmea_case: '{case}'. Must be new|new_env|design_change."}

        import_cases = ("new_env", "design_change")
        if case in import_cases and not state.get("dfmea_import_path"):
            return {"error": f"dfmea_import_path required for case '{case}'."}

        return {}   # routing happens via conditional edge reading dfmea_case directly


# ── 2. DFMEA RAG Context ──────────────────────────────────────────────────────

DFMEA_RAG_PROMPT = ChatPromptTemplate.from_messages([
    ("system", """You are an automotive FMEA expert.
Given retrieved engineering documents, extract and summarise:
1. Known failure modes for this component/subsystem
2. Historical risk ratings (S, O, D) if available
3. Relevant standards or design guidelines
Format as structured text that a DFMEA prompt can use directly.
Be concise and specific."""),
    ("human", "Component: {component}\nSubsystem: {subsystem}\n\nRetrieved context:\n{context}"),
])

FAISS_INDEX_PATH = "data/faiss_index"


class DFMEARagContextTool(BaseTool):
    name        = "dfmea_rag_context"
    description = "Retrieve engineering context from vector store to enrich DFMEA prompts."
    reads       = ["dfmea_component", "dfmea_subsystem"]
    writes      = ["dfmea_rag_context"]

    def __init__(self):
        self._store = None

    def _get_store(self):
        if self._store is None:
            self._store = FAISS.load_local(
                FAISS_INDEX_PATH,
                get_embeddings(),
                allow_dangerous_deserialization=True,
            )
        return self._store

    async def arun(self, state: AgentState) -> ToolResult:
        component  = state.get("dfmea_component", "")
        subsystem  = state.get("dfmea_subsystem", "")
        query      = f"failure modes {component} {subsystem} FMEA risk"

        store = self._get_store()
        docs  = store.max_marginal_relevance_search(query, k=5, fetch_k=15)
        context = "\n\n".join(d.page_content for d in docs)

        llm   = get_llm(temperature=0.0)
        chain = DFMEA_RAG_PROMPT | llm

        response = await chain.ainvoke({
            "component": component,
            "subsystem": subsystem,
            "context":   context,
        })

        return {"dfmea_rag_context": response.content}


# ── 3. Parse Import ───────────────────────────────────────────────────────────

class ParseImportTool(BaseTool):
    name        = "parse_import"
    description = "Parse an existing DFMEA xlsx into state (elements, functions, noise factors)."
    reads       = ["dfmea_import_path", "dfmea_case"]
    writes      = ["dfmea_elements", "dfmea_functions", "dfmea_noise_factors"]

    def run(self, state: AgentState) -> ToolResult:
        # Import your existing parser — no rewrite needed
        from routers_import_parse import parse_dfmea_xlsx   # your existing module

        path   = state["dfmea_import_path"]
        case   = state["dfmea_case"]
        parsed = parse_dfmea_xlsx(path)

        noise_factors = parsed.get("noise_factors", [])
        # new_env: replace noise factors (new environment, new stressors)
        # design_change: retain existing noise factors
        if case == "new_env":
            noise_factors = []   # will be regenerated by generate_elements

        return {
            "dfmea_elements":      parsed.get("elements", []),
            "dfmea_functions":     parsed.get("functions", []),
            "dfmea_noise_factors": noise_factors,
        }
